### ISSUE TITLE
Typescript Support & Rewrite in Typescript

### ISSUE THREAD

**Issue by waynevanson** [grabantot/react-cli#2]
Hi,

I firmly believe Typescript is a gift from the Gods and should be used as source code in this package.

This would enable intellisense of config files, easier contributions from community and enable a
`--typescript` flag in files.

You would only have templates in Typescript and it can be compiled to any version you like, such as `es6` and `es5` so it will be backwards compatible and more adoptable by other users.

What do you think about Typescript? What is your experience with Typescript?

Here are some flags we could have in the package too with this.
``` typescript
--typescript // enable typescript on project, using TS and TSX instead of JS and JSX
--types // generates a separate types file for component
```

If you'd like to perhaps see what your project looks like in Typescript, I can fork this repo and show you TS dev env.

**Comment by anatol-grabowski** [comment]
See my comment in another issue about why this was not implemented: one doesn't mix js and ts; to use ts one can edit the templates and change `"componentExtension": ".tsx"` in the `react-cli.config.json` if needed.
Then again if someone changes the templates then conversion functionality (func <-> class) gets broken (and probably I don't want to give it up) - what we would like to see ideally is support for custom templates, modules and cli-options.

About rewriting react-cli to typescript - that could be nice. If you intend to do so then please also create a `"watch": "nodemon -e ts -x \"tsc\""` (or something similar) script in `package.json` that watches .ts files for changes and rebuilds the project automatically. Without it the development will slow down substantially.

About converting all of the templates to ts and then just compiling them to js - I don't think this is going to work. We want users to be able to edit the templates directly and customize them however they like - indentation, commas, etc.

**Comment by waynevanson** [comment]
> Then again if someone changes the templates then conversion functionality (func <-> class) gets broken (and probably I don't want to give it up)

Is this a feature of the current release, where it can convert between the two? That's pretty cool if it is.

> About rewriting react-cli to typescript - that could be nice

Yeah mate, I'd love to. I will change the config and rewrite, presenting a pr when done.

 > We want users to be able to edit the templates directly and customize them however they like

Customisation is important, but there are many places to put the templates. The question is, what options are there and which options should be available?
+ config folder
+ their repository
+ ???

Config folder is what currently happens. 

Their repository could be an interesting one. The user might run a new cli command like `react-cli import` and then their templates would be copied to `.templates/`, so if they can change templates to suit their current project. If they like their new setup, they could use `react-cli export` to save it to their config template directory.

This also mean that they can use their editor of choice in a project they're already working on, instead of using `nano` or `vim` to create templates, which is not and aesthetic experience for some users.

I have many more suggestions and improvements I'd love to discuss, but I think I'll keep this within scope.

**Comment by anatol-grabowski** [comment]
> Is this a feature of the current release, where it can convert between the two?

yes this is in the current release. I used esprima to parse the file, find what's exported and convert func <-> class. You can try it try it yourself: 
1. `react-cli -f Cmp`, edit a functional component
2. now you decide that it has to be promoted to a class component
3. `react-cli -c Cmp`
4. check out a converted component

I wanted this project to help developers to manage components in the project through their whole life (create, add styles, add to index.js, convert, modify, keep propTypes up-to-date, move, rename, delete), not just generate templates.


I don't think that react-cli should download templates from the user repository - it's a deviation from the philosophy of doing one job and doing it good. What users can do is:
1. `git clone ssh://repo-with-the-templates`
2. `react-cli config repo-with-the-templates`

I think it is simple enough. What would be good is a way for users to set separate templates and config for separate projects. I think the best way to go about it is to use a logic similar to how eslint treats its configs - it starts from the current directory and goes up looking for the `.eslintrc.yml`. This way users can just put a `react-cli.config.json` in the root of their project. And `react-cli.config.json` should have a path to the templates directory or maybe even each template separately.

**Comment by waynevanson** [comment]
> I used esprima to parse the file ...

I googled it and was amazed, such a cool package. I saw a video from JSConf the other day where developers are attempting to write a JS compiler in Rust using similar logic, which was [cool](https://www.youtube.com/watch?v=_uD2pijcSi4).

>  I think the best way to go about it is to use a logic similar to how eslint treats its configs ... 

I agree. 

> I wanted this project to help developers to manage components in the project through their whole life 

This is a great goal. I will keep this in mind when exploring new features.
