### ISSUE TITLE
Modules and Testing

### ISSUE THREAD

**Issue by waynevanson** [grabantot/react-cli#3]
Hi Again,

I'm doing the rewrite in typescript and noticed that it isn't being exported as a module, so it's basically just a bunch of Javascript that runs via node. 

I'm thinking we can use [rollup](https://github.com/rollup/rollup) to bounce out the module. It might be necessary because currently Typescript bounces out to `./build/`, and this is the folder that would have to be uploaded to NPM, not the root `./`.

I've used rollup successfully before. Do you preference anything other than this? Otherwise I go ahead with configuration.

**Comment by anatol-grabowski** [comment]
what do you mean by "it isn't being exported as a module". I think it is a perfectly fine module that does its job.

I don't see any reason why `rollup` is necessary - I will look into it and give you my thought. Please keep your "rewrite to ts" free from `rollup`, feel free to change the structure of the project if needed. Keep in mind that it is completely customizable where typescript puts the compiled code. You can add `rollup` in a branch separate from "ts rewrite". My first impression about rollup: looks like a new fancy thing that we don't really need. How is it better than conventional webpack? I'll look into it.

...(edit) I see rollup is already in your fork, ok I'll check it out))

**Comment by waynevanson** [comment]
So I've been looking at rollup and realise it's into fit for the current purpose.

> "it isn't being exported as a module"

Exported as in bundled into a commonjs or ejs type.

Looking into it further, it's only really useful if we need to bundle the code into a single file or two (commonjs or ejs), which we don't. Because it runs using `#! bin/env/node`, the bundling is no use at this stage. It may come in useful later on if this is ever going to be implemented as a dev dependency, so I'll leave it out.

I'm just about done, and will let you look when it is ready.
